name: flutter_twilio_chat_conversations
description: A fork of original twilio_conversations plugin for Twilio Conversations.
version: 0.1.3
homepage: https://github.com/ShiftHackZ/Flutter-Twilio-Conversations-Plugin
repository: https://github.com/ShiftHackZ/Flutter-Twilio-Conversations-Plugin
issue_tracker: https://github.com/ShiftHackZ/Flutter-Twilio-Conversations-Plugin/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  enum_to_string: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  pigeon: ^1.0.7
  mockito: ^5.0.16
  uuid: ^3.0.5
  lints: ^1.0.1
  analyzer: ^2.1.0

dependency_overrides:
  analyzer: ^2.1.0

flutter:
  plugin:
    platforms:
      android:
        package: twilio.flutter.twilio_conversations
        pluginClass: TwilioConversationsPlugin
      ios:
        pluginClass: TwilioConversationsPlugin
